### ISSUE TITLE
Eppler 335 Camber Line Error

### ISSUE THREAD

**Issue by benjaminmoulton** [usuaero/AirfoilDatabase#8]
Hello,

I am creating a wing using an airfoil file (simply for the dxf output) from airfoiltools.com. I am including my files here.

When I run it I get the following error:

Traceback (most recent call last):
  File "simple_wing.py", line 3, in <module>
    wings = mx.Scene("wingscene.json")
  File "/home/ben/anaconda3/lib/python3.7/site-packages/machupX/scene.py", line 51, in __init__
    self._load_params(scene_input)
  File "/home/ben/anaconda3/lib/python3.7/site-packages/machupX/scene.py", line 111, in _load_params
    self.add_aircraft(key, airplane_file, state=state, control_state=control_state)
  File "/home/ben/anaconda3/lib/python3.7/site-packages/machupX/scene.py", line 292, in add_aircraft
    self._airplanes[airplane_name] = Airplane(airplane_name, airplane_input, self._unit_sys, self, init_state=state, init_control_state=control_state, v_wind=v_wind)
  File "/home/ben/anaconda3/lib/python3.7/site-packages/machupX/airplane.py", line 73, in __init__
    self._create_airfoil_database()
  File "/home/ben/anaconda3/lib/python3.7/site-packages/machupX/airplane.py", line 949, in _create_airfoil_database
    self._airfoil_database[key] = Airfoil(key, airfoil_dict[key])
  File "/home/ben/anaconda3/lib/python3.7/site-packages/airfoil_db/airfoil.py", line 98, in __init__
    self._initialize_geometry()
  File "/home/ben/anaconda3/lib/python3.7/site-packages/airfoil_db/airfoil.py", line 293, in _initialize_geometry
    self._calc_geometry_from_points()
  File "/home/ben/anaconda3/lib/python3.7/site-packages/airfoil_db/airfoil.py", line 513, in _calc_geometry_from_points
    raise CamberSolverNotConvergedError(self.name, camber_error)
airfoil_db.exceptions.CamberSolverNotConvergedError: The camber line solver for Eppler_335 failed to converge. Final error: 1.1074209973441599e-10

[Eppler_335.txt](https://github.com/usuaero/AirfoilDatabase/files/9143334/Eppler_335.txt)
[Wing_inertia.zip](https://github.com/usuaero/AirfoilDatabase/files/9143344/Wing_inertia.zip)

**Comment by corygoates** [comment]
You can overcome this by setting camber_termination_tol as a keyword argument in your Airfoil constructor. Just set it to 10e-9 or so.
